# Generated by Django 3.2.9 on 2022-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlcherWeb', '0001_initial'),
        ('users', '0002_profile_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(to='AlcherWeb.Post'),
        ),
    ]
