# Generated by Django 3.2.9 on 2022-08-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saved_posts',
        ),
    ]
